name: Android CI

on:
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Assemble release build
        run: ./gradlew bundleRelease
          
      - name: Build signed bundle
        uses: r0adkll/sign-android-release@v1
        with:
            releaseDirectory: app/build/outputs/bundle/release 
            signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
            alias: ${{ secrets.KEY_ALIAS }}
            keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}       
            keyPassword: ${{ secrets.KEY_PASSWORD }}
          
          
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
            serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
            packageName: com.infra.infraandroid
            releaseFiles: app/build/outputs/bundle/release/app-release.aab
            track: internal
